name: silvercore-bluebuild
description: My Linux desktop configuration
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest
modules:
  - from-file: rpm.yml
  - from-file: flatpak.yml
  - from-file: extensions.yml
  - type: signing
