services:

  main:
    container_name: main
    image: ghcr.io/jasonn3/build-container-installer
    volumes:
      - ./iso/main:/build-container-installer/build
    environment:
      VERSION: 40
      IMAGE_REPO: ghcr.io/arteeh
      IMAGE_NAME: silvercore
      IMAGE_TAG: latest
      VARIANT: Silverblue
      SECURE_BOOT_KEY_URL: https://raw.githubusercontent.com/arteeh/silvercore/main/cosign.pub
      ENROLLMENT_PASSWORD: universalblue
      ISO_NAME: build/Silvercore.iso
      WEB_UI: true
    privileged: true

  nvidia:
    container_name: nvidia
    image: ghcr.io/jasonn3/build-container-installer
    volumes:
      - ./iso/nvidia:/build-container-installer/build
    environment:
      VERSION: 40
      IMAGE_REPO: ghcr.io/arteeh
      IMAGE_NAME: silvercore-nvidia
      IMAGE_TAG: latest
      VARIANT: Silverblue
      SECURE_BOOT_KEY_URL: https://raw.githubusercontent.com/arteeh/silvercore/main/cosign.pub
      ENROLLMENT_PASSWORD: universalblue
      ISO_NAME: build/Silvercore-NVIDIA.iso
      WEB_UI: true
    privileged: true

  server:
    container_name: server
    image: ghcr.io/jasonn3/build-container-installer
    volumes:
      - ./iso/server:/build-container-installer/build
    environment:
      VERSION: 40
      IMAGE_REPO: ghcr.io/arteeh
      IMAGE_NAME: silvercore-server
      IMAGE_TAG: latest
      VARIANT: Server
      SECURE_BOOT_KEY_URL: https://raw.githubusercontent.com/arteeh/silvercore/main/cosign.pub
      ENROLLMENT_PASSWORD: universalblue
      ISO_NAME: build/Silvercore-Server.iso
      WEB_UI: true
    privileged: true

  cosmic:
    container_name: cosmic
    image: ghcr.io/jasonn3/build-container-installer
    volumes:
      - ./iso/cosmic:/build-container-installer/build
    environment:
      VERSION: 40
      IMAGE_REPO: ghcr.io/arteeh
      IMAGE_NAME: silvercore-cosmic
      IMAGE_TAG: latest
      VARIANT: Kinoite
      SECURE_BOOT_KEY_URL: https://raw.githubusercontent.com/arteeh/silvercore/main/cosign.pub
      ENROLLMENT_PASSWORD: universalblue
      ISO_NAME: build/Silvercore-Cosmic.iso
      WEB_UI: true
    privileged: true

