services:

  isogen-silvercore:
    container_name: isogen-silvercore
    image: ghcr.io/jasonn3/build-container-installer
    restart: no
    volumes:
      - /home/arteeh/isogenerator/main:/build-container-installer/build
    environment:
      - IMAGE_REPO="ghcr.io/arteeh"
      - IMAGE_NAME="silvercore"
      - IMAGE_TAG="br-master-40"
      - VERSION="40"
      - VARIANT="Silverblue"
      - ISO_NAME="Silvercore"
      - WEB_UI="true"
    privileged: true

  isogen-silvercore-server:
    container_name: isogen-silvercore-server
    image: ghcr.io/jasonn3/build-container-installer
    restart: no
    volumes:
      - /home/arteeh/isogenerator/server:/build-container-installer/build
    environment:
      - IMAGE_REPO="ghcr.io/arteeh"
      - IMAGE_NAME="silvercore-server"
      - IMAGE_TAG="br-master-40"
      - VERSION="40"
      - VARIANT="Server"
      - ISO_NAME="Silvercore-Server"
      - WEB_UI="true"
    privileged: true

  isogen-silvercore-nvidia:
    container_name: isogen-silvercore-nvidia
    image: ghcr.io/jasonn3/build-container-installer
    restart: no
    volumes:
      - /home/arteeh/isogenerator/nvidia:/build-container-installer/build
    environment:
      - IMAGE_REPO="ghcr.io/arteeh"
      - IMAGE_NAME="silvercore-nvidia"
      - IMAGE_TAG="br-master-40"
      - VERSION="40"
      - VARIANT="Silverblue"
      - ISO_NAME="Silvercore-NVIDIA"
      - WEB_UI="true"
    privileged: true
