  type: rpm-ostree
  repos:
    - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    - https://download.docker.com/linux/fedora/docker-ce.repo
  install:
    - tailscale
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  remove:
    - gnome-software
    - gnome-software-rpm-ostree
    - gnome-system-monitor
    - gnome-tweaks
    - gnome-tour
    - yelp
    - firefox
    - firefox-langpacks
    - htop
    - nvtop
